services:
  twitch-bot:
    image: ghcr.io/cha0s1nc/cha0s_b0t:latest
    restart: unless-stopped
    env_file:
      - .env

  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30